name: "Go: Run Tests"
on:
  push:
    paths:
      - "go/**"
      - .github/workflows/go-tests.yml
      - .github/actions/**
      - codeql-workspace.yml
    branches:
      - main
      - "rc/*"
  pull_request:
    paths:
      - "go/**"
      - .github/workflows/go-tests.yml
      - .github/actions/**
      - codeql-workspace.yml

env:
  GO_VERSION: '~1.22.0'

permissions:
  contents: read

jobs:
  test-linux:
    if: github.repository_owner == 'github'
    name: Test Linux (Ubuntu)
    runs-on: ubuntu-latest-xl
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up CodeQL CLI
        uses: ./.github/actions/fetch-codeql

      - name: Enable problem matchers in repository
        shell: bash
        run: 'find .github/problem-matchers -name \*.json -exec echo "::add-matcher::{}" \;'

      - name: Build
        run: |
          bazel run //go:create-extractor-pack

      - name: Cache compilation cache
        id: query-cache
        uses: ./.github/actions/cache-query-compilation
        with:
          key: go-qltest

      - name: Test
        run: |
          cd go
          make test cache="${{ steps.query-cache.outputs.cache-dir }}"

  check-code:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check that all Go code is autoformatted
        run: |
          cd go
          make check-formatting

      - name: Check checked-in generated code
        run: |
          bazel run //go:gen
          git add .
          git diff --exit-code HEAD || (
            echo "please run bazel run //go:gen"
            exit 1
          )

      - name: Compile qhelp files to markdown
        run: |
          cd go
          env QHELP_OUT_DIR=qhelp-out make qhelp-to-markdown

      - name: Upload qhelp markdown
        uses: actions/upload-artifact@v3
        with:
          name: qhelp-markdown
          path: go/qhelp-out/**/*.md
