name: "Go: Run Tests"
on:
  push:
    paths:
      - "go/**"
      - .github/workflows/go-tests.yml
      - .github/actions/**
      - codeql-workspace.yml
    branches:
      - main
      - "rc/*"
  pull_request:
    paths:
      - "go/**"
      - .github/workflows/go-tests.yml
      - .github/actions/**
      - codeql-workspace.yml

permissions:
  contents: read

jobs:
  test-linux:
    if: github.repository_owner == 'github'
    name: Test Linux (Ubuntu)
    runs-on: ubuntu-latest-xl
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run tests
        uses: ./go/actions/test
        with:
          run-code-checks: true

  qhelp:
    name: Test qhelp conversion
    runs-on: ubuntu-latest
    steps:
      - name: Compile qhelp files to markdown
        shell: bash
        run: |
          cd go
          env QHELP_OUT_DIR=qhelp-out make qhelp-to-markdown
      - name: Upload qhelp markdown
        uses: actions/upload-artifact@v3
        with:
          name: qhelp-markdown
          path: go/qhelp-out/**/*.md
